<?php

namespace PrestaShop\Bundle\CoreBundle;

use PrestaShop\Bundle\CoreBundle\DependencyInjection\PrestashopCoreExtension;
use Symfony\Component\DependencyInjection\Extension\ExtensionInterface;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class CoreBundle extends Bundle
{
    public function getContainerExtension(): ?ExtensionInterface
    {
        return new PrestashopCoreExtension(); // TODO: Change the autogenerated stub
    }
}
